os: windous
dist: xenial
sudo: true
compiler: gcc
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake

services:
  - docker

jobs:
  include:
    - name: "tests"
      script:
        - git submodule update --init --recursive
        - mkdir -p .build
        - cd .build
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh
