addons:
  apt:
    packages:
    - clang-3.7
    - lib32stdc++6
    - lib32z1-dev
    - libc6-dev-i386
    - linux-libc-dev
    - gcc-multilib
    - g++-multilib
    - nasm
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
language: cpp
sudo: false
compiler:
  - clang
